- hosts: all
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          ZUUL_BRANCH_REAL=${ZUUL_BRANCH:-master}
          # Workaround for puppet-ceph, where we need to checkout
          # puppet-openstack-integration from stable/pike when working on
          # stable/jewel.
          # Ceph Jewel works with Newton to Pike
          # Ceph Mimic works with Rocky to Stein
          if [[ "$ZUUL_BRANCH" == "stable/jewel" ]]; then
              ZUUL_BRANCH_REAL='stable/pike'
          fi
          if [[ "$ZUUL_BRANCH" == "stable/mimic" ]]; then
              ZUUL_BRANCH_REAL='stable/rocky'
          fi
          CLONEMAP=`mktemp`
          function cleanup {
              rm -f $CLONEMAP
          }
          trap cleanup EXIT
          cat > $CLONEMAP << EOF
          clonemap:
            - name: openstack/puppet-openstack-integration
              dest: puppet-openstack-integration
          EOF
          /usr/zuul-env/bin/zuul-cloner -m $CLONEMAP \
              --cache-dir /opt/git \
              --zuul-branch $ZUUL_BRANCH_REAL \
              https://opendev.org openstack/puppet-openstack-integration
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - include_role:
        name: bindep
      vars:
        bindep_dir: "src/opendev.org/openstack/puppet-openstack-integration"

    - name: Create folder for gems
      file:
        path: "{{ ansible_user_dir }}/workspace/puppet-openstack-integration/.bundled_gems"
        state: directory

    - name: Install bundler
      shell:
        cmd: |
          ruby <<EOF
          cmd = 'gem install bundler --no-rdoc --no-ri --verbose'
          if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.3.0') then
              cmd += ' -v 1.17.3'
          end
          system(cmd)
          EOF
      environment:
        GEM_HOME: "{{ ansible_user_dir }}/workspace/puppet-openstack-integration/.bundled_gems"
