- hosts: all
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          ./run_unit_tests.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
