- hosts: all
  tasks:
    - shell:
        cmd: |
          if [ "{{ puppet_gem_version }}" != "latest" ]; then
            export PUPPET_GEM_VERSION='~> {{ puppet_gem_version }}.0'
          fi
          mkdir .bundled_gems
          export GEM_HOME=`pwd`/.bundled_gems
          gem install bundler --version 1.17.3 --no-rdoc --no-ri --verbose
          $GEM_HOME/bin/bundle install --retry 3
          $GEM_HOME/bin/bundle exec rake spec SPEC_OPTS='--format documentation'
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
