- hosts: all
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          if [ "{{ puppet_gem_version }}" != "latest" ]; then
            export PUPPET_GEM_VERSION='~> {{ puppet_gem_version }}'
          fi
          # TODO(tobias-urdin): Remove when we dont pin rspec-puppet
          export RSPEC_PUPPET_VERSION='{{ rspec_puppet_version }}'
          ./run_unit_tests.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
