- hosts: all
  tasks:
    - shell:
        cmd: |
          export PUPPET_GEM_VERSION='~> {{ puppet }}'
          mkdir .bundled_gems
          export GEM_HOME=`pwd`/.bundled_gems
          export GEM_BIN_DIR=$GEM_HOME/bin
          ruby <<EOF
          cmd = 'gem install bundler --no-rdoc --no-ri --verbose --no-user-install --bindir=${GEM_BIN_DIR}'
          if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.3.0') then
              cmd += ' -v 1.17.3'
          end
          system(cmd)
          EOF
          $GEM_BIN_DIR/bundle install --retry 3
          # FUTURE_PARSER=yes is only supported by Puppet 3.x
          if [ "{{ puppet }}" -lt "4" ]; then
              export FUTURE_PARSER=yes
          fi
          $GEM_BIN_DIR/bundle exec rake syntax
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
